#pragma once

/**
 * @file config.h
 * @brief System configuration constants and device identification
 * 
 * This file contains configuration parameters for the EMS device including
 * device identification, MQTT communication settings, and system constants.
 * It provides functions for generating unique device IDs based on hardware MAC addresses.
 */

#include <Arduino.h>

// Device Identification Configuration
#define MAX_DEVICE_ID_CHARS   32                            //< Maximum characters in device ID string
#define DEVICE_ID_PREFIX      "EKEPC2-DDS238_"              //< Prefix for generated device IDs

// MQTT Communication Configuration
#define MQTT_TOPIC              "evse"                      //< Base MQTT topic for publishing
#define MQTT_PUBLISH_INTERVAL   30000                       //< MQTT publish interval in milliseconds (30 seconds)

// MQTT Broker Settings
#define MQTT_SERVER             "public.cloud.shiftr.io"    //< MQTT broker hostname
#define MQTT_USER               "public"                    //< MQTT broker username
#define MQTT_PW                 "public"                    //< MQTT broker password

/**
 * @brief Generate a unique device ID based on WiFi MAC address
 * 
 * Creates a device identifier using the last 3 bytes of the WiFi station MAC address.
 * The generated ID follows the format: DEVICE_ID_PREFIX + last 3 MAC bytes in hex.
 * This provides a shorter, more manageable device ID while maintaining uniqueness.
 * 
 * Example output: "EKEPC2-DDS238_A1B2C3"
 */
void generateDeviceID();

/**
 * @brief Get the current device ID string
 * 
 * Returns a pointer to the device ID string that was generated by generateDeviceID().
 * The device ID must be generated first before calling this function.
 * 
 * @return Pointer to null-terminated device ID string
 */
const char* getDeviceID();
